### PR TITLE
added saddle detection and avoid overflow for ints and bytes

### PR DESCRIPTION
**Pull request by carrino**
https://en.wikipedia.org/wiki/Marching_squares#Disambiguation_of_saddle_points

### CODE REVIEW

**Comment by miho** [comment]
Thanks for your contribution. I'll do a quick review before I merge your code.

**Comment by carrino** [comment]
added another commit to handle high and low boundries.  I have a dataset where high is more appropriate than 0.

**Comment by carrino** [comment]
2 more commits to add perf fix and also one of work around interpolation overshoot caused by field boundries.

**Comment by miho** [comment]
I was finally able to do a quick review. Thanks again for your contribution.

**Pull request merged**
